### ISSUE TITLE
PSF rewrite exploration checklist

### ISSUE THREAD

**Issue by benmontet** [afeinstein20/eleanor#190]
Hi everyone,

Here is the checklist of things we would like to do/explore. Please do suggest other things and I'll add them to the list! This is at present copied from our notes on slack.

- [ ] Can we use more accurate PRF models?
  - [ ] How do we build a fast analytic model of the 'true' PSF that can be fit at each cadence?
  - [ ] Add in that model into the 'models' class and let that be called with the current setup
  - [ ] Verify it does a good job
- [ ] Can we make better use of autodifferentiation?
  - [ ] Does this mean a full rewrite in tensorflow2 with adam? Is that fast?
  - [ ] Would alternatives like pytorch work just as well, or is tensorflow2 the best bet?
  - [ ] Can we build a system that uses not tf1.x that does as good a job as quickly with the current simple models we have?
- [ ] Can we leverage all PSF models to make better photometry?
  - [ ] How nearby a star can we use the psf results for as a 'regressor' to improve the photometry?
  - [ ] Do we win a lot by combining information from many stars together? Or is there other telescope information we can include?
  - [ ] Do we want to use the Guassian parameters here, or can some other type of PSF model parameters do much better?
  - [ ] Can we build a function that does these bits automatically?
